version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@postgres:5432/messaging
      REDIS_HOST: redis
      JWT_SECRET: hehe
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: messaging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
